name: CI-BUILD

on: [push]

jobs:
    # osx-build:
    #     name: Build OSX
    #     runs-on: macos-12 
    #     steps:
    #         - uses: actions/checkout@v4
    #         - uses: actions/setup-python@v5
    #           with:
    #             python-version: '3.10'
    #         - name: build
    #           run: |
    #             sudo python3 setup.py build_plugin
    #         - name: Upload OSX release
    #           uses: softprops/action-gh-release@v2
    #           with:
    #             path: build/*.zip

    windows-build:
        name: Build Win
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            
            - uses: actions/setup-python@v5
              with:
                python-version: '3.10'
            
            - name: ensure wheel
              run: |
                python -m pip install wheel

            - name: build
              run: |
                python setup.py build_plugin

            - name: Extract branch name
              id: extract_branch
              shell: cmd
              run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      
            - name: Upload Windows release
              uses: softprops/action-gh-release@v2
              with:
                tag_name: "${{ steps.extract_branch.outputs.branch }}-ustable"
                path: build/*.zip
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    # rocky-build:
    #     name: Build Linux
    #     runs-on: ubuntu-latest
    #     strategy:
    #       matrix:
    #         rocky-version: [ '8', '9' ]
    #     container:
    #       image: rockylinux/rockylinux:${{ matrix.rocky-version }}
    #     steps:
    #         - uses: actions/checkout@v4
    #         - uses: actions/setup-python@v5
    #           with:
    #             python-version: '3.10'
    #         - name: build
    #           run: |
    #             sudo python3 setup.py build_plugin
    #         - name: Upload Rocky ${{ matrix.rocky-version }} release
    #           uses: softprops/action-gh-release@v2
    #           with:
    #             path: build/*.zip